Output ./demo_filter.gif
Output ./demo_filter.mp4

Set Shell zsh
Set Theme "Builtin Solarized Light"
Set TypingSpeed 80ms
Set FontSize 22
Set Width 1800
Set Height 800

Type "vault-tasks -c ../.config/ -v ../test-vault filter"
Enter

Sleep 3s
Type "#tobuy 09/29"
Enter

Sleep 1.5s
# Scroll
Ctrl+J
Sleep 300ms
Ctrl+J
Sleep 300ms
Ctrl+J
Sleep 300ms
Ctrl+J
Sleep 300ms
Ctrl+J
Sleep 300ms
Ctrl+J
Sleep 300ms
Ctrl+J
Sleep 300ms
Ctrl+J
Sleep 300ms
Ctrl+J

Sleep 4s


# Stop vault-tasks
Ctrl+c
